feeds:
  - name: world_hydrogen
    url: "https://news.google.com/rss/search?q=hydrogen+project+OR+electrolyser+when:24m&hl=en&gl=US&ceid=US:en"
  - name: world_refinery
    url: "https://news.google.com/rss/search?q=refinery+project+OR+revamp+OR+upgrade+OR+modernization+when:24m&hl=en&gl=US&ceid=US:en"
  - name: world_chemicals
    url: "https://news.google.com/rss/search?q=chemical+plant+project+OR+ammonia+OR+methanol+OR+ethylene+when:24m&hl=en&gl=US&ceid=US:en"
  - name: world_water
    url: "https://news.google.com/rss/search?q=wastewater+treatment+OR+WWTP+OR+desalination+project+when:24m&hl=en&gl=US&ceid=US:en"
  - name: world_biofuels
    url: "https://news.google.com/rss/search?q=biodiesel+OR+HVO+OR+SAF+OR+renewable+diesel+project+when:24m&hl=en&gl=US&ceid=US:en"
  - name: emissions_abatement
    url: "https://news.google.com/rss/search?q=emissions+reduction+OR+decarbonization+OR+CCS+OR+methane+project+when:24m&hl=en&gl=US&ceid=US:en"
